version: "3"
services:
  node_backend:
    container_name: "server"
    build: .
    ports:
      - "49160:8000"
  pg:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "api"
      POSTGRES_PASSWORD: "password"